name: Github workflow
on: 
  push:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v2
      - name: Nodejs
        uses: actions/setup-node@v1
      - name: Install dependencies
        run: npm install
      - name: Run the test
        run: npm test